# Generated by Django 4.0.2 on 2022-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField(default=0)),
                ('interest_rate', models.FloatField()),
                ('manthly_repayment', models.IntegerField(default=0)),
                ('repayment_method', models.CharField(choices=[('revo', 'リボ'), ('installment_payment', '分割払')], max_length=50)),
            ],
        ),
    ]
